version: '3.8'

services:
  vite-app:
    image: node:20-alpine
    container_name: vite-test-page
    working_dir: /app
    volumes:
      - app-data:/app
      - .:/vite-template:ro
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "
      if [ ! -f /app/package.json ]; then
        echo 'First run detected, copying template files to volume...';
        cp -r /vite-template/* /app/ 2>/dev/null || true;
        cp -r /vite-template/.[^.]* /app/ 2>/dev/null || true;
      fi;
      npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

volumes:
  app-data:
    name: app-data