# Nixpacks configuration for Vite application

[phases.setup]
nixPkgs = ["nodejs_22_12"]

[phases.install]
cmds = [
  "echo 'Setting up Vite application...'",
  "npm install"
]

# For development with hot reload
[start]
cmd = "npm run dev -- --host 0.0.0.0 --port ${PORT:-5173}"

[variables]
NODE_ENV = "development"