[phases.setup]
# Install rsync for initial file copy
aptPkgs = ["rsync"]

[phases.build]
# Build commands
cmds = ["npm install", "npm run build"]

[start]
# Start command - runs startup.js which sets up mounted volume then starts Vite
cmd = "npm start"
